# Generated by Django 5.2.11 on 2026-03-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_total_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_rooms',
        ),
    ]
